name: Go
on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: self-hosted
    env:
      COV_BIN: /Users/chakrava/coverity-macosx-2021.03/bin

    steps:
    - uses: actions/checkout@v2
    - name: IO Scan
      id: prescription
      uses: synopsys-sig/intelligent-security-scan@48eedfcd42bc342a294dc495ac452797b2d9ff08
      with:
        stage: "IO"
        ioServerUrl: ${{secrets.IO_SERVER_URL}}
        ioServerToken: ${{secrets.IO_SERVER_TOKEN}}        
        workflowServerUrl: ${{secrets.WORKFLOW_SERVER_URL}}
        prescriptionDownloadURL: ${{secrets.PRESCRIPTION_DOWNLOAD_URL}}
        additionalWorkflowArgs: "--polaris.url=${{secrets.POLARIS_SERVER_URL}} --github.token=${{secrets.GH_ATOKEN}} --polaris.project.name=sig-chakrava/insecurebank --polaris.token=${{secrets.POLARIS_ACCESS_TOKEN}} --jira.auth.token=${{secrets.JIRA_TOKEN}} --sensitive.package.pattern='.*(.xml)' --jira.project.name=DEV --jira.api.url=https://dev-io.atlassian.net/rest/api/latest --jira.username=chakra.mithun@gmail.com --jira.issues.query=project=DEV --blackduck.project.name=insecure-bank:1.0.0 --blackduck.url=https://io-blackduck.dev.polaris.synopsys.com --blackduck.api.token=${{secrets.BLACKDUCK_TOKEN}}"
    
   - name: Incremental Analysis with Coverity
      if: ${{steps.prescription.outputs.sastScan == 'true' }}
      continue-on-error: true
      run: |
         URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/commits/${GITHUB_SHA}"
         FILES=$(curl -s -X GET -G $URL | jq -r '.files [] | .filename')
         echo $FILES | tr " " "\n" > polaris-files-to-scan.txt
         $COV_BIN/cov-configure --java
         rm -rf temp
         $COV_BIN/cov-run-desktop --dir temp --stream iostream --all --webapp-security --ignore-uncapturable-inputs true --present-in-reference false --exit1-if-defects true --url https://io-coverity.dev.polaris.synopsys.com --user iouser --password Io2021@15243 @@polaris-files-to-scan.txt

    - name: Software Composition Analysis with Black Duck
      if: ${{steps.prescription.outputs.scaScan == 'true' }}
      uses: blackducksoftware/github-action@v2
      with:
         args: '--blackduck.url="${{ secrets.BLACKDUCK_URL}}" --blackduck.api.token="${{ secrets.BLACKDUCK_TOKEN}}" --detect.tools="DETECTOR" --blackduck.trust.cert=true'
   
    - name: Synopsys Intelligent Security Scan
      if: ${{steps.prescription.outputs.sastScan == 'true' || steps.prescription.outputs.scaScan == 'true'}}
      uses: synopsys-sig/intelligent-security-scan@48eedfcd42bc342a294dc495ac452797b2d9ff08
      with:
        ioServerURL: ${{secrets.IO_SERVER_URL}}
        ioServerToken: ${{secrets.IO_SERVER_TOKEN}}
        workflowServerUrl: ${{secrets.WORKFLOW_SERVER_URL}}
        prescriptionDownloadURL: ${{secrets.PRESCRIPTION_DOWNLOAD_URL}}
        additionalWorkflowArgs: "--jira.assignee='Chakravarthy S M' --polaris.url=${{secrets.POLARIS_SERVER_URL}} --IS_SAST_ENABLED=${{steps.prescription.outputs.sastScan}} --IS_SCA_ENABLED=${{steps.prescription.outputs.scaScan}} --github.token=${{secrets.GH_ATOKEN}} --polaris.project.name=sig-chakrava/insecure-bank --polaris.token=${{secrets.POLARIS_ACCESS_TOKEN}} --jira.auth.token=${{secrets.JIRA_TOKEN}} --sensitive.package.pattern='.*(.xml)' --jira.project.name=DEV --jira.api.url=https://dev-io.atlassian.net --jira.username=chakra.mithun@gmail.com --jira.issues.query=project=DEV --blackduck.project.name=insecure-bank:1.0.0 --blackduck.url=https://io-blackduck.dev.polaris.synopsys.com --blackduck.api.token=${{secrets.BLACKDUCK_TOKEN}}  --slack.channel.id=C015LGE7RRQ --slack.token=xoxb-538932482230-1423237450497-IgjgmcTsFho5zxrdBC6Znan6"
        stage: "WORKFLOW"

    - name: Upload SARIF file
      if: ${{steps.prescription.outputs.sastScan == 'true' }}
      uses: github/codeql-action/upload-sarif@v1
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: workflowengine-results.sarif.json